export const API_ENDPOINTS = {
    LOGIN: "accounts/login/",
    REGISTER: "accounts/signup/",
    VERIFY_OTP: "accounts/verify/",
    LOGOUT: "/logout",
    FORGET_PASSWORD: "/forget-password",
    CATEGORIES: "products/category/",
    CATEGORIES_2: "/categories.json",
    CATEGORIES_ANCIENT: "/categories_ancient.json",
    FEATURED_CATEGORIES: "/featured_categories.json",
    COLLECTIONS: "/collections.json",
    BRANDS: "/brands.json",
    BRANDS_ANCIENT: "/brands_ancient.json",
    PRODUCTS: "products/viewproduct/",
    FEATURED_PRODUCTS: "products/viewproduct/",
    PRODUCTS_2: "/products_2.json",
    PRODUCTS_ANCIENT: "/products_ancient.json",
    FEATURED_PRODUCTS_ANCIENT: "/featured_products_ancient.json",
    TOP_SELLER_PRODUCTS: "/products_top_seller.json",
    ON_SELLING_PRODUCTS: "products/viewproduct/",
    PRODUCT: "/product.json",
    RELATED_PRODUCTS: "/related_products.json",
    BEST_SELLER_PRODUCTS: "/products_best_seller.json",
    NEW_ARRIVAL_PRODUCTS: "products/viewproduct/",
    POPULAR_PRODUCTS: "/products_popular.json",
    NEW_ARRIVAL_PRODUCTS_ANCIENT: "/products_new_arrival.json",
    FLASH_SALE_PRODUCTS: "products/viewproduct/",
    FLASH_SALE_PRODUCTS_ANCIENT: "/products_flash_sale_ancient.json",
    SHOPS: "/shops.json",
    SHOP: "/shop.json",
    SEARCH: "/search.json",
    ORDERS: "/orders.json",
    ORDER: "/order.json",

    // cart endpoints
    ADD_TO_CART: "activities/add_to_cart/",
    REMOVE_FROM_CART: "activities/remove_from_cart/",
    EDIT_CART: "activities/edit_cart_item/",
    VIEW_CART_ITEMS: "activities/view_cart_items/",

    // wislist endpoints
    VIEW_WISHLIST_ITEMS: "activities/view_wishlist_items/",
};
